#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

USER root
RUN apt-get update && \
    apt-get install -y iputils-ping curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER app

WORKDIR /app
EXPOSE 80
EXPOSE 81

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Assignment.ServiceA/Assignment.ServiceA.csproj", "Assignment.ServiceA/"]
RUN dotnet restore "./Assignment.ServiceA/./Assignment.ServiceA.csproj"
COPY . .
WORKDIR "/src/Assignment.ServiceA"
RUN dotnet build "./Assignment.ServiceA.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Assignment.ServiceA.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Assignment.ServiceA.dll"]