apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ .Values.networkpolicy.name }}
spec:
  podSelector:
    matchLabels:
      {{- include "servicea.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                kubernetes.io/metadata.name: kube-system