apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ .Values.networkpolicy.name }}
spec:
  podSelector:
    matchLabels:
      {{- include "serviceb.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.networkpolicy.ingress | nindent 4 }}