apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ .Values.networkpolicy.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkpolicy.name }}
  policyTypes:
  - Ingress