name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
    paths:
      - helm/**

permissions:
  contents: read

jobs:
  deploy-to-kubernetes:
    name: 'Deploy to Kubernetes'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/kubernetes-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.AKS_KUBE_CONFIG }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.x'

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install apis-umbrella-release ./helm/apis-umbrella
