name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
    paths:
      - helm/**

permissions:
  contents: read

jobs:
  gitversion:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: "./"
    outputs:
      versionout: ${{ steps.gitversionstep.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
          preferLatestVersion: true

      - name: Determine Version
        id: gitversionstep
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display GitVersion outputs (step output)
        run: |
          echo "SemVer: ${{ steps.gitversionstep.outputs.semVer }}"

  deploy-to-kubernetes:
    name: 'Deploy to Kubernetes'
    needs: gitversion
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
        installKubectl: true

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
      env:
        KUBE_CONFIG: ${{ secrets.AKS_KUBE_CONFIG }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Build Helm dependencies
      run: |
        helm dependency build ./helm/apis-umbrella

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install apis-umbrella-release-${{ needs.gitversion.outputs.versionout }} ./helm/apis-umbrella
