name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
    paths:
      - helm/**

permissions:
  contents: read

jobs:
  deploy-to-kubernetes:
    name: 'Deploy to Kubernetes'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install helm and kubectl
      uses: mirzakhany/install-helm-action@v1    
      with:
        k8s_config: ${{ secrets.AKS_KUBE_CONFIG }}

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install apis-umbrella-release ./helm/apis-umbrella
