name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitversion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true
    
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

  servicea:
    runs-on: ubuntu-latest
    needs: gitversion
    defaults:
      run:
        shell: bash
        working-directory: 'proj/Assignment/Assignment.ServiceA'
    steps:
    - name: Display GitVersion outputs (step output)
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

    - name: Build the Docker image for service A
      run: docker build . --file Dockerfile --tag servicea:${{ steps.gitversion.outputs.semVer }}
