name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitversion:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: './'
    outputs:
      versionout: ${{ steps.gitversionstep.outputs.semVer }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true
    
    - name: Determine Version
      id:   gitversionstep
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - name: Display GitVersion outputs (step output)
      run: |
        echo "SemVer: ${{ steps.gitversionstep.outputs.semVer }}"
        outputs:

  servicea:
    runs-on: ubuntu-latest
    environment: dev
    needs: gitversion
    defaults:
      run:
        working-directory: './proj/Assignment/Assignment.ServiceA'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build the Docker image for service A
      run: docker build . --tag servicea:${{ needs.gitversion.outputs.versionout }}
