name: 'Terraform destroy'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    env:
      RESOURCES_CONFIGURATION_FOLDER: './infra/modules/resources-configuration'
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      GITHUB_TOKEN: ${{secrets.TF_GITHUB_TOKEN}}

    defaults:
      run:
        shell: bash
        working-directory: ${{env.RESOURCES_CONFIGURATION_FOLDER}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ secrets.SA_NAME }}" \
          -backend-config="container_name=terraform-state" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=ms-assignment-config" \
          -backend-config="sas_token=${{ secrets.SA_TOKEN }}"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve